sample :drum_roll
wait(6)
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard
sample :drum_cymbal_hard